version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.0

    steps:
      - checkout

      - run:
          name: Run Tests
          command: npm test

      - run:
          name: Build the Application
          command: npm build

      - aws-s3/sync:
          from: build
          to: 's3://counts.tmf.zone'

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
